-- SOMANDO O VALOR TOTAL EM ESTOQUE, CONTAGEM DE PRODUTOS REGISTRADOS E QTD EM ESTOQUE USANDO O SUM E COUNT
SELECT 
COUNT(produto_id) as QTD_PRODUTOS_REGISTRADOS, 
SUM(preco_unitario) as VALOR_TOTAL, 
SUM(estoque) as QTD_DISPONIVEL 
FROM PRODUTOS;

-- SELECIONANDO O PRIMEIRO E ULTIMO PRODUTO USANDO O MIN E MAX
SELECT
MIN(DESCRICAO) AS PRIMEIRO_PRODUTO, 
MAX(DESCRICAO) AS ULITMO_PRODUTO
FROM PRODUTOS;

