SELECT Status, SUM(valor_total) AS TOTAL
FROM pedidos
GROUP BY status 
HAVING TOTAL < 3000 -- AGRUPANDO OS VALORES TOTAIS PELO STATUS DE PAGAMENTO MAS APENAS SE FOR MENOR QUE 3000 REAIS
ORDER BY TOTAL DESC; 