SELECT 
COUNT(produto_id) AS QTD_PRODUTOS_REGISTRADOS, 
SUM(preco_unitario) AS VALOR_TOTAL, 
SUM(estoque) AS QTD_DISPONIVEL 
FROM PRODUTOS AS TABELA_PRODUTOS; -- USANDO ALIASES PARA TROCAR OS NOMES DAS COLUNAS E TABELA