SELECT *
FROM (
    SELECT cliente_id AS CLIENTE_ID, SUM(valor_total) AS TOTAL_GASTO -- SUBCONSULTA NO FROM PARA CRIAR UMA TABELA TEMPORARIA
    FROM pedidos
    GROUP BY cliente_id
) AS RESUMO
WHERE TOTAL_GASTO > 1000
ORDER BY TOTAL_GASTO DESC;

